# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    working_directory: ~/app
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      #install node dependencies
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests
      - run: npm test
  deploy-app:
    docker:
      - image: circleci/node:latest
    working_directory: ~/app  
    steps:
      - checkout
      - run:
          name: Run setup script
          command: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "0a:6f:cc:a6:4a:d4:76:6d:4e:25:b6:62:85:76:1b:3b"
      # run build (prod) and test
      - run: npm build
      # setup docker instance for building and pushing
      - setup_remote_docker
      #build docker image
      - run: docker build -t tedthedev/react-portfolio-website:latest .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      #push to dockerhub
      - run: docker push tedthedev/react-portfolio-website:latest
      - run:
          name: Deploy container image to Heroku
          command: heroku container:push web
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy-app:
          requires:
            - build
          filters:
            branches:
              only: master